# Generated by Django 5.2 on 2026-07-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='소속')),
                ('license_no', models.CharField(blank=True, max_length=50, verbose_name='자격번호')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
            ],
            options={
                'verbose_name': '조종사',
                'verbose_name_plural': '조종사 목록',
                'db_table': 'pilot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AbsimTrackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polled_at', models.FloatField(verbose_name='폴링 시각 (Unix)')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('callsign', models.CharField(blank=True, max_length=20, verbose_name='Callsign')),
                ('gufi_id', models.CharField(blank=True, max_length=50, verbose_name='GufiID')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lon', models.FloatField(verbose_name='경도')),
                ('alt', models.FloatField(verbose_name='고도 (ft)')),
                ('hdg', models.FloatField(default=0.0, verbose_name='헤딩 (°)')),
                ('pitch', models.FloatField(default=0.0, verbose_name='피치 (°)')),
                ('roll', models.FloatField(default=0.0, verbose_name='롤 (°)')),
                ('spd', models.FloatField(default=0.0, verbose_name='지상속도 (kt)')),
                ('tas', models.FloatField(default=0.0, verbose_name='TAS (kt)')),
                ('cas', models.FloatField(default=0.0, verbose_name='CAS (kt)')),
                ('uam_status', models.CharField(blank=True, max_length=30, verbose_name='UAM 상태')),
                ('udp_connected', models.BooleanField(default=False, verbose_name='UDP 연결 상태')),
            ],
            options={
                'verbose_name': 'ABSim 항적 이력',
                'verbose_name_plural': 'ABSim 항적 이력 목록',
                'db_table': 'absim_track_log',
                'indexes': [models.Index(fields=['polled_at'], name='idx_absim_track_polled_at')],
            },
        ),
        migrations.CreateModel(
            name='FlightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_plan_snapshot', models.JSONField(blank=True, help_text='세션 시작 시점 FlightPlan.to_dict() 고정 — 이후 FPL이 수정/삭제돼도 안 바뀜', null=True, verbose_name='FPL 스냅샷')),
                ('callsign', models.CharField(max_length=20, verbose_name='Callsign')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('end_reason', models.CharField(blank=True, choices=[('manual', '수동 종료'), ('timeout', '타임아웃 자동 종료')], max_length=10, verbose_name='종료 사유')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('flight_plan', models.ForeignKey(blank=True, help_text='Free Flight인 경우 비워둠', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_sessions', to='flight_planning.flightplan', verbose_name='Flight Plan')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_sessions', to='data_management.pilot', verbose_name='조종사')),
            ],
            options={
                'verbose_name': '비행 세션',
                'verbose_name_plural': '비행 세션 목록',
                'db_table': 'flight_session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FlightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='발생 시각')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='카테고리')),
                ('description', models.TextField(verbose_name='설명')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data_management.flightsession')),
            ],
            options={
                'verbose_name': '특이사항',
                'verbose_name_plural': '특이사항 목록',
                'db_table': 'flight_event',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(verbose_name='타임스탬프 (Unix)')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lon', models.FloatField(verbose_name='경도')),
                ('alt_ft', models.FloatField(verbose_name='고도 (ft)')),
                ('ias_kt', models.FloatField(verbose_name='IAS (kt)')),
                ('tas_kt', models.FloatField(default=0.0, verbose_name='TAS (kt)')),
                ('gs_kt', models.FloatField(default=0.0, verbose_name='지상속도 (kt)')),
                ('heading', models.FloatField(verbose_name='헤딩 (°)')),
                ('pitch', models.FloatField(verbose_name='피치 (°)')),
                ('roll', models.FloatField(verbose_name='롤 (°)')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='추가 파라미터')),
                ('session', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='flight_data', to='data_management.flightsession')),
            ],
            options={
                'verbose_name': '비행 데이터',
                'verbose_name_plural': '비행 데이터 목록',
                'db_table': 'flight_data',
                'indexes': [models.Index(fields=['session', 'timestamp'], name='idx_session_timestamp')],
            },
        ),
    ]
