# Generated by Django 5.2 on 2026-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdata',
            name='alt_ft',
            field=models.FloatField(blank=True, null=True, verbose_name='고도 (ft)'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='gs_kt',
            field=models.FloatField(blank=True, null=True, verbose_name='지상속도 (kt)'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='heading',
            field=models.FloatField(blank=True, null=True, verbose_name='헤딩 (°)'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='ias_kt',
            field=models.FloatField(blank=True, null=True, verbose_name='IAS (kt)'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='pitch',
            field=models.FloatField(blank=True, null=True, verbose_name='피치 (°)'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='roll',
            field=models.FloatField(blank=True, null=True, verbose_name='롤 (°)'),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='tas_kt',
            field=models.FloatField(blank=True, null=True, verbose_name='TAS (kt)'),
        ),
    ]
