# Generated by Django 5.2 on 2026-07-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alter_flightdata_alt_ft_alter_flightdata_gs_kt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsession',
            name='archive_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='아카이브 파일 경로'),
        ),
        migrations.AddField(
            model_name='flightsession',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='설정되면 FlightData/AbsimTrackLog는 DB에서 삭제되고 archive_path 파일에만 존재', null=True, verbose_name='아카이브 시각'),
        ),
    ]
