# Generated by Django 5.2 on 2026-08-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_flightsession_archive_path_flightsession_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absimtracklog',
            name='alt',
            field=models.FloatField(blank=True, null=True, verbose_name='고도 (ft)'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='cas',
            field=models.FloatField(blank=True, null=True, verbose_name='CAS (kt)'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='hdg',
            field=models.FloatField(blank=True, null=True, verbose_name='헤딩 (°)'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='pitch',
            field=models.FloatField(blank=True, null=True, verbose_name='피치 (°)'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='roll',
            field=models.FloatField(blank=True, null=True, verbose_name='롤 (°)'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='spd',
            field=models.FloatField(blank=True, null=True, verbose_name='지상속도 (kt)'),
        ),
        migrations.AlterField(
            model_name='absimtracklog',
            name='tas',
            field=models.FloatField(blank=True, null=True, verbose_name='TAS (kt)'),
        ),
    ]
