# Generated by Django 5.2 on 2026-07-18 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='이름')),
                ('aircraft_type', models.CharField(blank=True, max_length=50, verbose_name='기종')),
                ('dep', models.CharField(blank=True, max_length=8, verbose_name='출발지 ICAO')),
                ('arr', models.CharField(blank=True, max_length=8, verbose_name='목적지 ICAO')),
                ('eta', models.DateTimeField(help_text='EOBT는 이 값에서 역산됨 (CLAUDE.md §8 참고)', verbose_name='도착 예정시각 (ETA)')),
                ('departure_name', models.CharField(blank=True, max_length=30, verbose_name='출발 지점명')),
                ('departure_lat', models.FloatField(verbose_name='출발 위도')),
                ('departure_lon', models.FloatField(verbose_name='출발 경도')),
                ('departure_alt', models.FloatField(verbose_name='출발 고도 (ft)')),
                ('departure_velocity', models.FloatField(default=0, verbose_name='출발 속도 (kt)')),
                ('arrival_name', models.CharField(blank=True, max_length=30, verbose_name='도착 지점명')),
                ('arrival_lat', models.FloatField(verbose_name='도착 위도')),
                ('arrival_lon', models.FloatField(verbose_name='도착 경도')),
                ('arrival_alt', models.FloatField(verbose_name='도착 고도 (ft)')),
                ('arrival_velocity', models.FloatField(default=0, verbose_name='도착 속도 (kt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': 'Flight Plan',
                'verbose_name_plural': 'Flight Plan 목록',
                'db_table': 'flight_plan',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightPlanWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='순서')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='지점명')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lon', models.FloatField(verbose_name='경도')),
                ('alt', models.FloatField(verbose_name='고도 (ft)')),
                ('velocity', models.FloatField(default=0, verbose_name='속도 (kt)')),
                ('flight_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='flight_planning.flightplan')),
            ],
            options={
                'verbose_name': '경유점',
                'verbose_name_plural': '경유점 목록',
                'db_table': 'flight_plan_waypoint',
                'ordering': ['seq'],
                'unique_together': {('flight_plan', 'seq')},
            },
        ),
    ]
