# Generated by Django 5.2 on 2026-07-18 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlanInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_plan_name', models.CharField(max_length=100, verbose_name='FPL 이름 (스냅샷)')),
                ('target_model_name', models.CharField(max_length=50, verbose_name='대상 Model')),
                ('callsign', models.CharField(max_length=20, verbose_name='Callsign')),
                ('gufi_id', models.CharField(max_length=50, verbose_name='GufiID')),
                ('eobt', models.DateTimeField(blank=True, null=True, verbose_name='EOBT (계산값)')),
                ('dashboard_injection_id', models.IntegerField(blank=True, null=True, verbose_name='Dashboard injection_id')),
                ('dashboard_flight_plan_id', models.IntegerField(blank=True, null=True, verbose_name='Dashboard flight_plan_id')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP 상태 코드')),
                ('success', models.BooleanField(default=False, verbose_name='성공 여부')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='오류 메시지')),
                ('injected_at', models.DateTimeField(auto_now_add=True, verbose_name='전송 시각')),
                ('flight_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injections', to='flight_planning.flightplan')),
            ],
            options={
                'verbose_name': 'Flight Plan Injection 이력',
                'verbose_name_plural': 'Flight Plan Injection 이력',
                'db_table': 'flight_plan_injection',
                'ordering': ['-injected_at'],
            },
        ),
    ]
